config/routes.rb
Rails.application.routes.draw do

  get 'payments/buy'

  ActiveAdmin.routes(self)
  resources :items do

    member do
      get 'approve' => "items#approve", as: 'approve'
      get 'ban' => "items#ban", as: 'ban'
    end
  end

  devise_for :users

  resources :walls do
    member do
      get 'frame/:instance_id' => "walls#frame", as: 'frame'
      get 'control' => "walls#control", as: 'control'
      delete 'remove_background'
      delete 'remove_logo'
      get 'activate_prompt'
      post 'activation'
      resources :items, as: 'wall_uploaded_images', only: [:new, :create]
      get "test_socket" => "walls#test_sockets"
      get "history" => "walls#history"
    end
  end

  get 'instagram/webhook' => 'instagram#webhook'
  post 'instagram/webhook' => 'instagram#webhook'

  get "dashboard" => "walls#index"
  root "pages#landing"

  post "fastspring/webhook" => "fastspring#webhook"

end

app/views/pages/landing.html.erb
<div id="banner">
    <div id="banner-content">
      <div class="tagline">
        Interactive social photo wall
      </div>
      <div class="description">
        Hook up a projector and get your
        interactive installation running
        in less then 5 minutes.
      </div>
      <div class="form">
        <% if Wall.example %>
          <%= link_to Wall.example, class: "btn btn-primary btn-lg btn-hype" do %>
            <i class="fa fa-play"></i>&nbsp;
            See it in action
          <% end %>
        <% end %>
      </div>
    </div>
</div>
<div class="landing-body">
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="feature">
        <h1><i class="fa fa-instagram icon"></i> Social integration</h1>
        <span class="description">Collect photos from Instagram and Twitter hashtag.</span>
      </div>
    </div>
    <div class="col-md-6">
      <div class="feature">
        <h1><i class="fa fa-upload"></i> Direct upload</h1>
        <span class="description">Upload photos directly from your local collection.</span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="feature">
        <h1><i class="fa fa-wrench"></i> Wall customisation</h1>
        <span class="description">Make your wall look and feel unique.</span>
      </div>
    </div>
    <div class="col-md-6">
       <div class="feature">
        <h1><i class="fa fa-eye"></i> Moderation</h1>
        <span class="description">Require photo approval before showing them on wall.</span>
      </div>
    </div>
  </div>

  <% unless current_user %>
    <div class="jumbotron get-started">
      <div class="row">
        <div class="col-md-6">
          <h1>Get started!</h1></br>
          <h2><span class="strikeout">$20/month</span> FREE</h2>
          <div class="description">You can use hypewall completely free while it is in beta!</div>
        </div>
        <div class="col-md-6 sign-up">
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= devise_error_messages! %>
            <div class="form-group">
              <%= f.label :email %><br />
              <%= f.email_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :password %><br />
              <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
            </div>
            <div class="form-group"><%= f.submit "Sign up", class: "btn btn-primary btn-lg btn-hype btn-block" %></div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>