config/routes.rb
Rails.application.routes.draw do

  get 'payments/buy'

  ActiveAdmin.routes(self)
  resources :items do

    member do
      get 'approve' => "items#approve", as: 'approve'
      get 'ban' => "items#ban", as: 'ban'
    end
  end

  devise_for :users

  resources :walls do
    member do
      get 'frame/:instance_id' => "walls#frame", as: 'frame'
      get 'control' => "walls#control", as: 'control'
      delete 'remove_background'
      delete 'remove_logo'
      get 'activate_prompt'
      post 'activation'
      resources :items, as: 'wall_uploaded_images', only: [:new, :create]
      get "test_socket" => "walls#test_sockets"
      get "history" => "walls#history"
    end
  end

  get 'instagram/webhook' => 'instagram#webhook'
  post 'instagram/webhook' => 'instagram#webhook'

  get "dashboard" => "walls#index"
  root "pages#landing"

  post "fastspring/webhook" => "fastspring#webhook"

end

app/models/wall.rb
class Wall < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  def self.example
    Wall.find_by_id(ENV['EXAMPLE_WALL_ID'] || 1)
  end

  include Rails.application.routes.url_helpers

  BACKGROUND_STYLES = ['center','tile','stretch']
  FONT_COLORS = ['light','dark']
  FONT_STYLES = ['helvetica','lobster']

  has_attached_file :background_image, :styles => { :thumb => "300x300>" }, :default_url => "/images/:style/missing.png"
  has_attached_file :logo
  validates_attachment_content_type :background_image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

  has_many :wall_roles
  has_many :users, through: :wall_roles
  has_many :items, dependent: :destroy

  validates :name, presence: true
  validates :hashtag, presence: true

  accepts_nested_attributes_for :items, :allow_destroy => true

  before_save :hashtag_cleanup
  def hashtag_cleanup
    hashtag.gsub!('#','')
  end

  def has_logo?
    logo.file?
  end

  def has_background?
    background_image.file?
  end

  def instagram_subscribe(webhook)
    Thread.new do |t|
      Instagram.create_subscription('tag', "#{webhook}", object_id: hashtag)
      get_instagram_images
      t.exit
    end
  end

  def recent_instagram_images
    items = []
    Instagram.tag_recent_media(hashtag).each do |instagram_image|
      unless Item.find_by_original_id(instagram_image.id).present?
        items.push Item.create(
          original_id: instagram_image.id,
          user_id: instagram_image.user.id,
          url: instagram_image.images.standard_resolution.url,
          wall_id: self.id)
      end
    end
    return items
  end

  def new_items
    recent_instagram_images
  end

  def instagram_subscription
    (Instagram.subscriptions.select{ |subscription|
      subscription['object_id'] == self.hashtag }).first
  end

  def instagram_unsubscribe
    Instagram.delete_subscription(id: instagram_subscription.id)
  end

  def owner
    wall_roles.order('created_at').first.user
  end

  def is_pro?
    owner.is_pro?
  end

end

app/controllers/walls_controller.rb
class WallsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :frame]
  before_action :set_wall, only: [:edit, :update, :destroy, :control,
   :remove_background, :remove_logo, :test_sockets, :history]

  # GET /walls
  def index
    @menu = 'dashboard'
    @walls = current_user.walls
  end

  # GET /walls/1
  def show
    @wall = Wall.friendly.find(params[:id])
    authenticate_user! unless @wall == Wall.example
    render layout: 'presentation'
  end

  # GET /walls/new
  def new
    @wall = Wall.new
  end

  # GET /walls/1/edit
  def edit
  end

  # POST /walls
  def create
    @wall = Wall.new(wall_params)
    if @wall.save
      WallRole.create(user: current_user, wall: @wall)
      @wall.instagram_subscribe("#{root_url}instagram/webhook")
      redirect_to edit_wall_path(@wall), notice: 'Wall was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /walls/1
  def update
    @old_hashtag = @wall.hashtag.dup
    if @wall.update(wall_params)
      if @wall.hashtag != @old_hashtag
        @wall.instagram_unsubscribe
        @wall.images.destroy_all
        @wall.instagram_subscribe("#{root_url}instagram/webhook")
      end
      redirect_to edit_wall_path(@wall), notice: 'Wall was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /walls/1
  def destroy
    @wall.destroy
    redirect_to walls_url, notice: 'Wall was successfully destroyed.'
  end

  def control
    @images = @wall.items.limit(ApplicationHelper.control_wall_size)
  end

  def history
    @items = @wall.items.order(created_at: :desc).paginate(:page => params[:page], :per_page => 6)
  end

  def remove_background
    @wall.background_image = nil
    @wall.save
    redirect_to edit_wall_path(@wall)
  end

  def remove_logo
    @wall.logo = nil
    @wall.save
    redirect_to edit_wall_path(@wall)
  end

  def test_sockets
    # this method is used to test pushing through websockets
    # load this method and look for changes on the wall control
    push_to_item_control(@wall.items.first)
    push_to_wall(@wall.items.first)
    render text: "This is used to test websockets"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wall
      @wall = current_user.walls.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wall_params
      params.require(:wall).permit(:name, :hashtag, :description, :background_image, :background_style, :logo, :require_image_approval, :font_style, :font_color, :background_color)
    end
end

app/helpers/walls_helper.rb
module WallsHelper

  def parse_hypecode(text)
    unless text.blank?
      raw simple_format(text.gsub(/(#[^\s]+)/,'<span class=\'large\'>\1</span>'))
    end
  end
end

app/views/walls/_approve_menu.html.erb
<div class="controls <%= item.status %>">
  <% if item.status != 'approved' %>
    <%= link_to approve_item_path(item), remote: true do -%><i class="fa fa-check"></i>Approve<% end %>
  <% else %>
    <i class="fa fa-check"></i>Approve
  <% end %>
  |
  <% if item.status != 'banned' %>

    <%= link_to ban_item_path(item), remote: true do -%>
      <i class="fa fa-times"></i>Block photo
    <% end %>
    <%= link_to ban_user_wall_path(item.wall_id, item.id), :method => :post, remote: true do -%>
      <i class="fa fa-times"></i>Block user
    <% end %>
  <% else %>
    <i class="fa fa-times"></i>Block
  <% end %>
</div>

app/views/walls/_form.html.erb
<%= form_for(@wall, class: 'form') do |f| %>
  <% if @wall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wall.errors.count, "error") %> prohibited this wall from being saved:</h2>

      <ul>
      <% @wall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-4">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :hashtag %>
        <%= f.text_field :hashtag, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.check_box :require_image_approval %>
        <%= f.label :require_image_approval %>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/walls/activate_prompt.html.erb
<div class="container">

  <%= form_tag(activation_wall_path(@wall), method: "post") do %>
    <%= label_tag(:activation_code, "Paste your activation code here to use your wall") %>
    <%= text_field_tag(:activation_code) %>
    <%= submit_tag("Activate") %>
  <% end %>

  <p>Don't have an activation code?</p>

  <p>Click <%= link_to "here", "http://sites.fastspring.com/hypewall/product/hypewall" %>
    to buy one
  </p>

</div>

app/views/walls/control.html.erb
<div class="container">
  <h1>Images control</h1>
  <%= link_to "List banned users", list_banned_users_wall_path%>

  <div id="control">
  <% @images.each do |image| %>
    <%= render partial: 'items/item', locals: { item: image } %>
  <% end %>
  </div>

  <script>
    var dispatcher = new WebSocketRails('<%= websocket_host %>');
    channel = dispatcher.subscribe('item_control_<%= @wall.id %>');
    channel.bind('new', function(image_box_partial) {
      control_div = $("#control")
      if (control_div.children().length >= '<%= control_wall_size %>') {
        control_div.children().slice('<%= control_wall_size - 1 %>').remove();
        control_div.prepend(image_box_partial);
      }
    });
  </script>
</div>

app/views/walls/edit.html.erb
<div  id="wall-edit-preview"
      style="background-image: url('<%= @wall.background_image.url %>'); background-color: <%= @wall.background_color %>"
      class="<%= @wall.background_style %>">

<div id="info">

    <div id="description">
      <%= image_tag @wall.logo.url, class: 'logo' if @wall.has_logo? %>

      <!-- Logo upload -->
      <p>
        <% if @wall.has_logo? %>
          <button class="btn btn-default" data-tool-box-open="change-logo">
            <i class="fa fa-upload"></i> Change logo
          </button>
          <%= link_to "Remove", remove_logo_wall_path(@wall), class: "btn btn-danger", method: :delete %>
        <% else %>
          <button class="btn btn-default" data-tool-box-open="change-logo">
            <i class="fa fa-upload"></i> Upload logo
          </button>
        <% end %>

      <p>
      <div class="logo-tool-box tool-box hide" data-tool-box="change-logo">
        <%= form_for(@wall, class: 'form') do |f| %>
          <div class="form-group">
            <%= f.label :logo %>
            <%= f.file_field :logo %>
          </div>
          <%= f.submit "Upload", class: "btn btn-primary" %>
          <div class="btn btn-default" data-tool-box-close="change-logo">Cancel</div>
        <% end %>
      </div>

      <div class="description" data-tool-box-open="edit-description">
        <span class="<%= @wall.font_color %> <%= @wall.font_style %>">
          <%= parse_hypecode @wall.description %>
        </span>
        <button class="btn btn-default" data-tool-box-open="edit-description">
          <i class="fa fa-edit"></i> <%= @wall.description.blank? ? "Add description" : "Edit description" %>
        </button>
      </div>
      <div class="tool-box hide description-editor" data-tool-box="edit-description">
        <%= form_for(@wall, class: 'form') do |f| %>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control large-textarea' %>
          </div>
          <div class="form-group">
            <%= f.label :font_color %>
            <%= f.select :font_color, Wall::FONT_COLORS %>
          </div>
          <div class="form-group">
            <%= f.label :font_style %>
            <%= f.select :font_style, Wall::FONT_STYLES %>
          </div>
          <div class="form-group">
            <%= f.submit class: "btn btn-primary" %>
            <div class="btn btn-default" data-tool-box-close="edit-description">Cancel</div>
          </div>
        <% end %>
      </div>
    </div>

    <!-- Background upload -->
    <div id="btn-bg-select">
      <button class="btn btn-default" data-tool-box-open="change-bg">
        <i class="fa fa-upload"></i> Change background
      </button>
      <% if @wall.has_background? %>
        <%= link_to "Remove", remove_background_wall_path(@wall), class: "btn btn-danger", method: :delete %>
      <% end %>
    </div>
    <div id="bg-select" class="tool-box hide" data-tool-box="change-bg">
      <%= form_for(@wall, class: 'form') do |f| %>
        <div class="form-group">
          <%= f.label :background_image %>
          <%= f.file_field :background_image%>
        </div>
        <div class="form-group">
          <%= f.label :background_style %></br>
          <%= f.select :background_style, Wall::BACKGROUND_STYLES %>
        </div>
        <div class="form-group">
          <%= f.label :background_color %></br>
          <%= f.text_field :background_color, class: 'form-control colorpicker' %>
        </div>
        <%= f.submit "Update", class: "btn btn-primary" %>
        <div class="btn btn-default" data-tool-box-close="change-bg">Cancel</div>
      <% end %>
    </div>

</div>

app/views/walls/history.html.erb
<% @items.each do |item|  %>
  <div id="control">
    <%= render partial: 'items/item', locals: { item: item } %>
  </div>
<% end %>

<%= will_paginate @items, renderer: BootstrapPagination::Rails %>

app/views/walls/index.html.erb
<div class="container">
  <div class="wall-list">


  <h1>Subscription level: <%= current_user.subscription_level %></h1>

  <% if @walls.any? %>
    <h1>My walls</h1>
    <table class="table table-hover">
      <tr>
        <th>Name</th>
        <% if current_user.is_pro? %>
          <th class="tool-column">Edit</th>
        <% end %>
        <th class="tool-column">Upload</th>
        <th class="tool-column">Control</th>
        <th class="tool-column">Delete</th>
        <th class="tool-column">Activate</th>
      </tr>
      <% @walls.each do |wall| %>
        <tr>
          <td> <%= link_to wall.name, wall %> </td>
          <% if wall.is_pro? %>
          <td class="tool-column">
            <%= link_to edit_wall_path(wall) do %> <i class="fa fa-pencil"></i> <% end %>
          </td>
          <% end %>
          <td class="tool-column">
            <%= link_to new_wall_uploaded_image_path(wall) do %> <i class="fa fa-upload"></i> <% end %>
          </td>
          <td class="tool-column">
            <%= link_to control_wall_path(wall) do %> <i class="fa fa-eye"></i> <% end %>
          </td>
          <td class="tool-column">
            <%= link_to wall, method: :delete, data: { confirm: "Are you sure?" } do %> <i class="fa fa-times"></i> <% end %>
          </td>
          <!-- temporary for testing -->
          <td class="tool-column">
          <%= link_to activate_prompt_wall_path(wall) do %> <p>activate</p> <% end %>
          </td>
          <!-- /temporary -->
        </tr>
      <% end %>
    </table>
    <%= link_to new_wall_path, class: 'btn btn-primary' do %>
      <i class="fa fa-plus"></i> New Wall
    <% end %>
  <% else %>
    <div class="jumbotron">
      <h1>Create your first wall</h1>
      <p>
        It seems you are new around here. </br>
        Don't worry you will have your first HypeWall running in no time.
      </p>
      <p>
        <%= link_to new_wall_path, class: 'btn btn-primary btn-lg' do %>
          <i class="fa fa-plus"></i> Create my wall
        <% end %>
      </p>

    </div>
  <% end %>

  </div>

</div>

app/views/walls/list_banned_users.html.erb
<h1>List of banned users</h1>
<table>
	<tr>
		<th>User Id</th>
	    <th>Link</th>
	</tr>

<% @banned.each do |b| %>
	<tr>
		<td><%= b.user_id %></td>
		<td><%=link_to "Unban", unban_user_wall_path(b.wall_id, b.id), :method => :post%></td>
	</tr>
<% end %>

</table>

app/views/walls/new.html.erb
<div class="container">
  <h1>New wall</h1>

  <%= render 'form' %>

  <%= link_to 'Back', walls_path %>
</div>

app/views/walls/show.html.erb
<div id="info">
  <div id="description">
    <p> <%= image_tag @wall.logo.url, class: "logo" if @wall.has_logo? %> </p>
    <div class="description <%= @wall.font_color %> <%= @wall.font_style %>">
      <%= parse_hypecode @wall.description %>
    </div>
  </div>

  <div id="wall-menu-trigger">
    <div id="wall-menu">
      <% if current_user %>
        <%= link_to edit_wall_path(@wall) do %><span class="fa fa-pencil"></span><% end %>
      <% end %>
      <a href="#" class="fullscreen"><span class="fa fa-expand"></span></a>
    </div>
  </div>
</div>
<canvas id="wall_bricks" data-images='<%= @wall.items.to_json %>' data-websocket-host="<%= websocket_host %>" data-wall-id="<%= @wall.id %>"></canvas>