config/routes.rb
Rails.application.routes.draw do

  get 'payments/buy'

  ActiveAdmin.routes(self)
  resources :items do

    member do
      get 'approve' => "items#approve", as: 'approve'
      get 'ban' => "items#ban", as: 'ban'
    end
  end

  devise_for :users

  resources :walls do
    member do
      get 'frame/:instance_id' => "walls#frame", as: 'frame'
      get 'control' => "walls#control", as: 'control'
      delete 'remove_background'
      delete 'remove_logo'
      get 'activate_prompt'
      post 'activation'
      resources :items, as: 'wall_uploaded_images', only: [:new, :create]
      get "test_socket" => "walls#test_sockets"
      get "history" => "walls#history"
    end
  end

  get 'instagram/webhook' => 'instagram#webhook'
  post 'instagram/webhook' => 'instagram#webhook'

  get "dashboard" => "walls#index"
  root "pages#landing"

  post "fastspring/webhook" => "fastspring#webhook"

end

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54228011-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="">
<head>
  <title>HypeWall</title>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Lobster|Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= stylesheet_link_tag    'landing', media: 'all' if @landing_page %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>
<body>


<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to root_path, class:"navbar-brand"  do %>
        <%= image_tag 'logo-small.png', id: "logo" %>
      <% end %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li class="<%= 'active' if @menu == 'dashboard' %>"><%= link_to 'Dashboard', dashboard_path %></a></li>
          <% if @wall %>
            <li> <%= link_to 'Show wall', @wall %> </li>
          <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-user"></i> <%= current_user.name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Account settings", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to new_user_registration_path do %><strong>Create account</strong><% end %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

  <div class="container">
    <% if notice %><p class="alert alert-success"><%= notice %></p><% end %>
    <% if alert %><p class="alert alert-danger"><%= alert %></p><% end %>
  </div>
  <%= yield %>

  <%= render partial: 'layouts/google_analytics' %>
</body>
</html>

app/views/layouts/presentation.html.erb
<!DOCTYPE html>
<html class="">

  <head>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lobster|Open+Sans' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'presentation' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body style="background-image: url('<%= @wall.background_image.url %>'); background-color: <%= @wall.background_color %>" class="<%= @wall.background_style %>">
    <%= yield %>
    <%= render partial: 'layouts/google_analytics' %>
  </body>

</html>